### ISSUE TITLE
jogl-samples library not found

### ISSUE THREAD

**Issue by tempest766** [elect86/jogl-samples#42]
not very reassuring that upon unzipping and running netbeans 8.2 the first thing that pops up is 
("jogl-library" could not be found in jogl-samples) and no mention of this error in the readme, 
but instead a cryptic statement about manually adding all the jar files under [dependencies].

Well, since the zip archive is a netbeans project layout, it doesn't seem right that I'd have to manually add jar files that are already part of the directory layout.  Why would they not already be referenced in the project XML files as library dependencies if they are themselves included in the project?

What gives?  At most it is a broken project.  At the least, the documentation on how to build it is inadequate.

Help?

**Comment by elect86** [comment]
Hey tempest766,

I feel you, I also dislike when a project shows errors on the very beginning.

Sorry for that, believe me when I say I'm the first who would like this to change.

However this project is actually obsolete and need a general rewrite (maybe in kotlin) with lwjgl (because jogl is even dead in the meanwhile) and gradle (or maven).

But unfortunately this is a very busy time for me and I have a lot of things with a much higher priority on my todo list.

Anyway, we are totally open to contributions: after all, it was the main purpose when I created the organization.

If you are willing to invest some of your time and energy into make this project working again and useful for other users, please don't hesitate, I'll add you as a collaborator immediately :)

**Comment by tempest766** [comment]
thanks for the followup.  my only interest in the samples was to get a better feel for the capabilities and stability of the jogl framework.  I used gl4java 12+ years ago and it was kind of primitive.  I needed some demos/samples that build quickly and demonstrate the capabilities without jumping thru a lot of hoops.  isn't lack of platform dependent hoops what java is all about? LOL

Anyway, will close this ticket, as you said the samples are obsolete.  Still looking for a better "current" primer/wiki for jogl and related tools like newt.

**Comment by elect86** [comment]
As you wish

If you change idea, you shall look into [`uno`](https://github.com/kotlin-graphics/uno-sdk) for a nice wrapper around the counterpart of newt for lwjgl, that is glfw.
